apiVersion: v1
kind: Service
metadata:
  name: deception-java-dev
  labels:
    app.kubernetes.io/name: java-dev
    app.kubernetes.io/part-of: deception
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: java-dev
    app.kubernetes.io/part-of: deception
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deception-java-dev
  labels:
    app.kubernetes.io/name: java-dev
    app.kubernetes.io/part-of: deception
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: java-dev
      app.kubernetes.io/part-of: deception
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-dev
        app.kubernetes.io/part-of: deception
    spec:
      containers:
        - name: java-dev
          image: deception-java-dev
          ports:
            - containerPort: 8080
