apiVersion: v1
kind: Service
metadata:
  name: deception-python-dev
  labels:
    app.kubernetes.io/name: python-dev
    app.kubernetes.io/part-of: deception
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: python-dev
    app.kubernetes.io/part-of: deception
  ports:
    - port: 8081
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deception-python-dev
  labels:
    app.kubernetes.io/name: python-dev
    app.kubernetes.io/part-of: deception
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: python-dev
      app.kubernetes.io/part-of: deception
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-dev
        app.kubernetes.io/part-of: deception
    spec:
      containers:
        - name: python-dev
          image: deception-python-dev
          ports:
            - containerPort: 5000
