apiVersion: v1
kind: PersistentVolume
metadata:
  name: deception-persistent-volume
  labels:
    app.kubernetes.io/name: persistent-volume
    app.kubernetes.io/part-of: deception
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "efs-storage-class"
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <fs-id>
