apiVersion: v1
kind: Service
metadata:
  name: benchmark-deception-sut-worst-case-python
  labels:
    app.kubernetes.io/name: sut-worst-case-python
    app.kubernetes.io/part-of: benchmark-deception
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sut-worst-case-python
    app.kubernetes.io/part-of: benchmark-deception
  ports:
    - port: 8080
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-deception-sut-worst-case-python
  labels:
    app.kubernetes.io/name: sut-worst-case-python
    app.kubernetes.io/part-of: benchmark-deception
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sut-worst-case-python
      app.kubernetes.io/part-of: benchmark-deception
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sut-worst-case-python
        app.kubernetes.io/part-of: benchmark-deception
    spec:
      containers:
        - name: benchmark-deception-sut-worst-case-python
          image: benchmark-sut-worst-case-python
          ports:
            - containerPort: 5000
