apiVersion: v1
kind: Service
metadata:
  name: benchmark-tb-locust
  labels:
    app.kubernetes.io/name: tb-locust
    app.kubernetes.io/part-of: benchmark
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tb-locust
    app.kubernetes.io/part-of: benchmark
  ports:
    - port: 8089
      targetPort: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-tb-locust
  labels:
    app.kubernetes.io/name: tb-locust
    app.kubernetes.io/part-of: benchmark
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tb-locust
      app.kubernetes.io/part-of: benchmark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tb-locust
        app.kubernetes.io/part-of: benchmark
    spec:
      volumes:
        - name: benchmark-folder
          persistentVolumeClaim:
            claimName: benchmark-deception-performance-data-persistent-volume-claim
      containers:
        - name: tb-locust
          image: benchmark-tb-locust
          ports:
            - containerPort: 8089
          volumeMounts:
            - mountPath: /opt/locust/cvs_exports
              name: benchmark-folder
              subPath: benchmark_exports
            # For Debugging
            - mountPath: /opt/fileSystem
              name: benchmark-folder
