apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deception-persistent-volume-claim
  namespace: deception-dev
  labels:
    app.kubernetes.io/name: persistent-volume-claim
    app.kubernetes.io/part-of: deception
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      app.kubernetes.io/name: persistent-volume
      app.kubernetes.io/part-of: deception
